# Generated by Django 4.1.1 on 2022-09-08 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Биография'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='Customers/2022/09/09/default-avatar-profile-icon-vector-social-media-user-photo-18304237_NLdrISN.jpg', upload_to='Customers/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
